spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: event-visualizer-local
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      schema-registry: http://localhost:8081

server:
  port: 8082
